---
Name: slider
Before:
  - 'mysite/*'
---
Page_Controller:
  extensions:
    - SliderPageControllerExtension
Page:
  extensions:
    - SliderPageExtension
---
Only:
  moduleexists: 'Fluent'
---
SliderSlide:
  extensions:
    - 'FluentExtension'
