---
Name: slider
Before:
  - 'mysite/*'
---
Page_Controller:
  extensions:
    - SliderPageControllerExtension
Page:
  extensions:
    - SliderPageExtension
SliderSlide:
  extensions:
    - 'FluentExtension'